# this is just a example how to declare two boxes in one vagrantfile

Vagrant.configure("2") do |config|
    config.vm.define "server" do |server|
      server.vm.box = "myUbuntu2204"
    end
  
    config.vm.define "client" do |client|
      client.vm.box = "myUbuntu2204"
    end
  
  end